/**
 * MRS_TPV - Preload seguro (context bridge)
 * Solo exponer lo necesario al renderer.
 */
const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('mrsTpv', {
  getConfig: () => ipcRenderer.invoke('get-config'),
  setConfig: (config) => ipcRenderer.invoke('set-config', config),
  getPbUrl: () => ipcRenderer.invoke('get-pb-url'),
  hasPbUsers: () => ipcRenderer.invoke('has-pb-users'),
  runPbMigrations: () => ipcRenderer.invoke('run-pb-migrations'),
  ensurePbFields: () => ipcRenderer.invoke('ensure-pb-fields'),
  pbAdminListUsers: () => ipcRenderer.invoke('pb-admin-list-users'),
  pbAdminGetUser: (recordId) => ipcRenderer.invoke('pb-admin-get-user', recordId),
  pbAdminCreateUser: (payload) => ipcRenderer.invoke('pb-admin-create-user', payload),
  pbAdminUpdateUser: (recordId, patch) => ipcRenderer.invoke('pb-admin-update-user', recordId, patch),
  pbAdminDeleteUser: (recordId) => ipcRenderer.invoke('pb-admin-delete-user', recordId),
  getVersion: () => ipcRenderer.invoke('get-version'),
  getLicenseStatus: () => ipcRenderer.invoke('get-license-status'),
  activateLicenseKey: (key) => ipcRenderer.invoke('activate-license-key', key),
  importLicenseFile: () => ipcRenderer.invoke('import-license-file'),
  copyText: (text) => ipcRenderer.invoke('copy-text', text),
  checkForUpdates: (opts) => ipcRenderer.invoke('check-for-updates', opts || {}),
  getUpdateStatus: () => ipcRenderer.invoke('get-update-status'),
  downloadUpdate: (opts) => ipcRenderer.invoke('download-update', opts || {}),
  installDownloadedUpdate: () => ipcRenderer.invoke('install-downloaded-update'),
  getSession: () => ipcRenderer.invoke('get-session'),
  saveSession: (session) => ipcRenderer.invoke('save-session', session),
  clearSession: () => ipcRenderer.invoke('clear-session'),
  getCategorias: () => ipcRenderer.invoke('get-categorias'),
  saveCategorias: (data) => ipcRenderer.invoke('save-categorias', data),
  getProductos: () => ipcRenderer.invoke('get-productos'),
  saveProductos: (data) => ipcRenderer.invoke('save-productos', data),
  getCajaActual: () => ipcRenderer.invoke('get-caja-actual'),
  saveCajaActual: (data) => ipcRenderer.invoke('save-caja-actual', data),
  getClientes: () => ipcRenderer.invoke('get-clientes'),
  saveClientes: (data) => ipcRenderer.invoke('save-clientes', data),
  getTickets: () => ipcRenderer.invoke('get-tickets'),
  saveTickets: (data) => ipcRenderer.invoke('save-tickets', data),
  getFacturas: () => ipcRenderer.invoke('get-facturas'),
  saveFacturas: (data) => ipcRenderer.invoke('save-facturas', data),
  getGestionPresupuestos: () => ipcRenderer.invoke('get-gestion-presupuestos'),
  saveGestionPresupuestos: (data) => ipcRenderer.invoke('save-gestion-presupuestos', data),
  getGestionAlbaranes: () => ipcRenderer.invoke('get-gestion-albaranes'),
  saveGestionAlbaranes: (data) => ipcRenderer.invoke('save-gestion-albaranes', data),
  getGestionSeries: () => ipcRenderer.invoke('get-gestion-series'),
  saveGestionSeries: (data) => ipcRenderer.invoke('save-gestion-series', data),
  getReparaciones: () => ipcRenderer.invoke('get-reparaciones'),
  saveReparaciones: (data) => ipcRenderer.invoke('save-reparaciones', data),
  getReparacionesSeries: () => ipcRenderer.invoke('get-reparaciones-series'),
  saveReparacionesSeries: (data) => ipcRenderer.invoke('save-reparaciones-series', data),
  getDistribuidores: () => ipcRenderer.invoke('get-distribuidores'),
  saveDistribuidores: (data) => ipcRenderer.invoke('save-distribuidores', data),
  getRegistrosFiscales: () => ipcRenderer.invoke('get-registros-fiscales'),
  saveRegistrosFiscales: (data) => ipcRenderer.invoke('save-registros-fiscales', data),
  getAuditTrail: () => ipcRenderer.invoke('get-audit-trail'),
  saveAuditTrail: (data) => ipcRenderer.invoke('save-audit-trail', data),
  printTicket: (ticket, config) => ipcRenderer.invoke('print-ticket', { ticket, config }),
  printFactura: (factura, config) => ipcRenderer.invoke('print-factura', { factura, config }),
  printRepairReceipt: (receipt, config) => ipcRenderer.invoke('print-repair-receipt', { receipt, config }),
  exportToPdf: (html, defaultPath) => ipcRenderer.invoke('export-to-pdf', { html, defaultPath }),
  exportToCsv: (content, defaultPath) => ipcRenderer.invoke('export-to-csv', { content, defaultPath }),
  selectLogo: () => ipcRenderer.invoke('select-logo'),
  backupData: () => ipcRenderer.invoke('backup-data'),
  restoreData: () => ipcRenderer.invoke('restore-data'),
  getPrinters: () => ipcRenderer.invoke('get-printers')
});
